### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by zqm64** [xiaomi-ulysse-wip/android_device_xiaomi_ulysse-common#1]
- [ ] Fix RIL
- [ ] Fix Power-off alarm
- [ ] Fix sepolicy (especially FP)
- [ ] Fix 4.9 kernel support (FPC Blob and path)
- [ ] Update Audio XMLs
- [ ] Update proprietary-files.txt

**Comment by rofikkerneldev** [comment]
@zqm64 what SE policy (FP)  issue mean ? 

its finger print prevent selinux goto Enforcing or else?

**Comment by zqm64** [comment]
@rsoft3d Missing sepolicy rules, need to make them

**Comment by rofikkerneldev** [comment]
@zqm64 ok ,now it more undestandable now
